import 'package:cloud_firestore/cloud_firestore.dart';

class FirestoreDataLoader {
  static const Map<String, List<String>> bolivianRegions = {
    'La Paz': [
      'Centro',
      'Sopocachi',
      'Miraflores',
      'San Jorge',
      'Calacoto',
      'San Miguel',
      'Achumani',
      'Cota Cota',
      'Obrajes',
      'Zona Sur (General)',
      'El Alto - Villa Adela',
      'El Alto - Ciudad Satélite',
      'El Alto - Villa Ingenio',
      'El Alto - Senkata',
      'Achachicala',
      'Pura Pura',
      'Irpavi',
      'Següencoma',
      'Tembladerani',
      'Villa Fátima',
    ],
    'Cochabamba': [
      'Centro (Cercado)',
      'Muyurina',
      'Sarco',
      'Quillacollo',
      'Sacaba',
      'Tiquipaya',
      'Zona Norte (General)',
      'Av. América',
      'Hipódromo',
      'Zona Sur (General)',
      'Parque Lincoln',
      'Temporal',
      'Valle Hermoso',
      'Av. Blanco Galindo (Km)',
      'Colcapirhua',
      'Vinto',
      'Punata',
    ],
    'Santa Cruz': [
      'Centro (1er Anillo)',
      'Equipetrol Norte',
      'Equipetrol Sur',
      'Zona Norte (4to Anillo)',
      'Zona Sur (Doble Vía La Guardia)',
      'Zona Este (Av. Tres Pasos)',
      'Urubó',
      'Warnes',
      'Montero',
      'Cotoca',
      'Palmasola',
      'Barrio Sirari',
      'Los Cusis',
      'Radial 13',
      'El Remanso',
      'Paurito',
      'Plan 3000',
    ],
    'Oruro': [
      'Centro Histórico',
      'Zona Norte',
      'Zona Sur',
      'Vinto (Oruro)',
      'Urbanización Gualberto Villarroel',
      'Barrio 24 de Junio',
      'Challapampita',
      'Casco Viejo',
      'Terminal de Buses',
    ],
    'Potosí': [
      'Centro',
      'Villa Imperial',
      'Cantumarca',
      'San Clemente',
      'Zona Alta',
      'Zona Baja',
      'Barrio Obrero',
      'Betanzos',
      'Uyuni (Ciudad)',
    ],
    'Chuquisaca (Sucre)': [
      'Casco Histórico',
      'Zona Central',
      'Barrio Petrolero',
      'Zona San Lázaro',
      'Zona de Abasto',
      'D-3 (Barrio Universitario)',
      'D-5 (Azari)',
      'Yotala',
    ],
    'Tarija': [
      'Centro (Cercado)',
      'Zona Central',
      'Barrio Senac',
      'San Blas',
      'Valle de la Concepción',
      'Yacuiba',
      'Villamontes',
      'Bermejo',
      'El Tejar',
      'San Gerónimo',
    ],
    'Beni (Trinidad)': [
      'Centro',
      'Copeco',
      'Villa Vecinal',
      'Moxos',
      'Reyes',
      'Riberalta',
      'Guayaramerín',
    ],
    'Pando (Cobija)': [
      'Centro',
      'Barrio Avaroa',
      'Villa Busch',
      'El Mirador',
      'Puerto Rico',
      'Bolpebra',
    ],
  };

  Future<Map<String, List<String>>> loadRegions() async {
    await Future.delayed(
      const Duration(milliseconds: 50),
    );
    return bolivianRegions;
  }
}
