// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ59-_LGwiGpNJb1fCTIdiyFIbPCgwVqw',
    appId: '1:39000178233:web:5d37996a1920f30df0d7e8',
    messagingSenderId: '39000178233',
    projectId: 'comercial-785c5',
    authDomain: 'comercial-785c5.firebaseapp.com',
    storageBucket: 'comercial-785c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ59-_LGwiGpNJb1fCTIdiyFIbPCgwVqw',
    appId: '1:39000178233:android:5d37996a1920f30df0d7e8',
    messagingSenderId: '39000178233',
    projectId: 'comercial-785c5',
    storageBucket: 'comercial-785c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ59-_LGwiGpNJb1fCTIdiyFIbPCgwVqw',
    appId: '1:39000178233:ios:5d37996a1920f30df0d7e8',
    messagingSenderId: '39000178233',
    projectId: 'comercial-785c5',
    storageBucket: 'comercial-785c5.firebasestorage.app',
    iosBundleId: 'com.comercial.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ59-_LGwiGpNJb1fCTIdiyFIbPCgwVqw',
    appId: '1:39000178233:ios:5d37996a1920f30df0d7e8',
    messagingSenderId: '39000178233',
    projectId: 'comercial-785c5',
    storageBucket: 'comercial-785c5.firebasestorage.app',
    iosBundleId: 'com.comercial.app',
  );
}
